### YamlMime:ManagedReference
items:
  - uid: com.microsoft.azure.batch.protocol.models._batch_error_exception
    id: _batch_error_exception
    parent: com.microsoft.azure.batch.protocol.models
    children:
      - 'com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException(final String,final Response<ResponseBody>)'
      - 'com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException(final String,final Response<ResponseBody>,final BatchError)'
      - com.microsoft.azure.batch.protocol.models._batch_error_exception.body()
    href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
    langs:
      - java
    name: BatchErrorException
    nameWithType: BatchErrorException
    fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException
    type: Class
    source:
      remote: &ref_0
        path: src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
        branch: master
        repo: 'https://github.com/Azure/azure-batch-sdk-for-java'
      path: src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
      startLine: 17
    package: com.microsoft.azure.batch.protocol.models
    summary: <p><span data-ttu-id="a7948-101">無効な応答の例外のスロー <xref uid="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false">BatchError</xref>情報。</span><span class="sxs-lookup"><span data-stu-id="a7948-101">Exception thrown for an invalid response with <xref uid="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false">BatchError</xref> information.</span></span> </p>
    syntax: &ref_1
      content: public class BatchErrorException
    inheritance:
      - java.lang.Object
      - RestException
  - uid: 'com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException(final String,final Response<ResponseBody>)'
    id: 'BatchErrorException(final String,final Response<ResponseBody>)'
    parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
    href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
    langs:
      - java
    name: 'BatchErrorException(final String message, final Response<ResponseBody> response)'
    nameWithType: 'BatchErrorException.BatchErrorException(final String message, final Response<ResponseBody> response)'
    fullName: 'com.microsoft.azure.batch.protocol.models.BatchErrorException.BatchErrorException(final String message, final Response<ResponseBody> response)'
    overload: com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
      startLine: 24
    package: com.microsoft.azure.batch.protocol.models
    summary: |-
      <p><span data-ttu-id="a7948-102">新しいインスタンスを初期化、 <xref uid="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false">BatchErrorException</xref>クラスです。</span><span class="sxs-lookup"><span data-stu-id="a7948-102">Initializes a new instance of the <xref uid="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false">BatchErrorException</xref> class.</span></span></p>
      <p></p>
    syntax:
      content: 'public BatchErrorException(final String message, final Response<ResponseBody> response)'
      parameters:
        - id: message
          type: 3d93591e
          description: <p><span data-ttu-id="a7948-103">例外メッセージや、メッセージが利用できない場合は、応答コンテンツ</span><span class="sxs-lookup"><span data-stu-id="a7948-103">the exception message or the response content if a message is not available</span></span> </p>
        - id: response
          type: 4f402e61
          description: <p><span data-ttu-id="a7948-104">HTTP 応答</span><span class="sxs-lookup"><span data-stu-id="a7948-104">the HTTP response</span></span> </p>
  - uid: 'com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException(final String,final Response<ResponseBody>,final BatchError)'
    id: 'BatchErrorException(final String,final Response<ResponseBody>,final BatchError)'
    parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
    href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
    langs:
      - java
    name: 'BatchErrorException(final String message, final Response<ResponseBody> response, final BatchError body)'
    nameWithType: 'BatchErrorException.BatchErrorException(final String message, final Response<ResponseBody> response, final BatchError body)'
    fullName: 'com.microsoft.azure.batch.protocol.models.BatchErrorException.BatchErrorException(final String message, final Response<ResponseBody> response, final BatchError body)'
    overload: com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
      startLine: 35
    package: com.microsoft.azure.batch.protocol.models
    summary: |-
      <p><span data-ttu-id="a7948-105">新しいインスタンスを初期化、 <xref uid="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false">BatchErrorException</xref>クラスです。</span><span class="sxs-lookup"><span data-stu-id="a7948-105">Initializes a new instance of the <xref uid="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false">BatchErrorException</xref> class.</span></span></p>
      <p></p>
    syntax:
      content: 'public BatchErrorException(final String message, final Response<ResponseBody> response, final BatchError body)'
      parameters:
        - id: message
          type: 3d93591e
          description: <p><span data-ttu-id="a7948-106">例外メッセージや、メッセージが利用できない場合は、応答コンテンツ</span><span class="sxs-lookup"><span data-stu-id="a7948-106">the exception message or the response content if a message is not available</span></span> </p>
        - id: response
          type: 4f402e61
          description: <p><span data-ttu-id="a7948-107">HTTP 応答</span><span class="sxs-lookup"><span data-stu-id="a7948-107">the HTTP response</span></span> </p>
        - id: body
          type: 93de0ef9com.microsoft.azure.batch.protocol.models._batch_error
          description: <p><span data-ttu-id="a7948-108">逆シリアル化された応答本文</span><span class="sxs-lookup"><span data-stu-id="a7948-108">the deserialized response body</span></span> </p>
  - uid: com.microsoft.azure.batch.protocol.models._batch_error_exception.body()
    id: body()
    parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
    href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
    langs:
      - java
    name: body()
    nameWithType: BatchErrorException.body()
    fullName: BatchError com.microsoft.azure.batch.protocol.models.BatchErrorException.body()
    overload: com.microsoft.azure.batch.protocol.models._batch_error_exception.body*
    type: Method
    source:
      remote: *ref_0
      path: src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
      startLine: 40
    package: com.microsoft.azure.batch.protocol.models
    syntax:
      content: public BatchError body()
      return:
        type: com.microsoft.azure.batch.protocol.models._batch_error
references:
  - uid: 3d93591e
    spec.java:
      - name: final String
        fullName: final String
  - uid: 4f402e61
    spec.java:
      - name: final Response<ResponseBody>
        fullName: final Response<ResponseBody>
  - uid: com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException*
    name: BatchErrorException
    nameWithType: BatchErrorException.BatchErrorException
    fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException.BatchErrorException
    package: com.microsoft.azure.batch.protocol.models
  - uid: 93de0ef9com.microsoft.azure.batch.protocol.models._batch_error
    spec.java:
      - name: 'final '
        fullName: 'final '
      - uid: com.microsoft.azure.batch.protocol.models._batch_error
        name: BatchError
        fullName: com.microsoft.azure.batch.protocol.models.BatchError
        href: com.microsoft.azure.batch.protocol.models._batch_error.yml
  - uid: com.microsoft.azure.batch.protocol.models._batch_error_exception.body*
    name: body
    nameWithType: BatchErrorException.body
    fullName: BatchError com.microsoft.azure.batch.protocol.models.BatchErrorException.body
    package: com.microsoft.azure.batch.protocol.models
  - uid: com.microsoft.azure.batch._create_tasks_error_exception
    parent: com.microsoft.azure.batch
    href: com.microsoft.azure.batch._create_tasks_error_exception.yml
    name: CreateTasksErrorException
    nameWithType: CreateTasksErrorException
    fullName: com.microsoft.azure.batch.CreateTasksErrorException
    type: Class
    summary: '<p><span data-ttu-id="a7948-109">ときにスローされる例外、 <xref uid="" data-throw-if-not-resolved="false">TaskOperations #createTasks(String, List)</xref>操作が終了しました。</span><span class="sxs-lookup"><span data-stu-id="a7948-109">The exception that is thrown when the <xref uid="" data-throw-if-not-resolved="false">TaskOperations#createTasks(String, List)</xref> operation is terminated.</span></span> </p>'
    syntax:
      content: public class CreateTasksErrorException
  - uid: com.microsoft.azure.batch.protocol.models._batch_error_exception
    parent: com.microsoft.azure.batch.protocol.models
    href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
    name: BatchErrorException
    nameWithType: BatchErrorException
    fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException
    type: Class
    summary: <p><span data-ttu-id="a7948-110">無効な応答の例外のスロー <xref uid="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false">BatchError</xref>情報。</span><span class="sxs-lookup"><span data-stu-id="a7948-110">Exception thrown for an invalid response with <xref uid="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false">BatchError</xref> information.</span></span> </p>
    syntax: *ref_1
  - uid: com.microsoft.azure.batch.protocol.models._batch_error
    parent: com.microsoft.azure.batch.protocol.models
    href: com.microsoft.azure.batch.protocol.models._batch_error.yml
    name: BatchError
    nameWithType: BatchError
    fullName: com.microsoft.azure.batch.protocol.models.BatchError
    type: Class
    summary: <p><span data-ttu-id="a7948-111">Azure Batch のサービスから受信したエラー応答。</span><span class="sxs-lookup"><span data-stu-id="a7948-111">An error response received from the Azure Batch service.</span></span> </p>
    syntax:
      content: public class BatchError