### YamlMime:ManagedReference
items:
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615
    id: _provis0d423877466065f42d44d66a2d881615
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    children:
      - 'com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.httpResponseVerification(int,String)'
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.yml
    langs:
      - java
    name: ProvisioningServiceClientExceptionManager
    nameWithType: ProvisioningServiceClientExceptionManager
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientExceptionManager
    type: Class
    source:
      remote: &ref_0
        path: provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/exceptions/ProvisioningServiceClientExceptionManager.java
        branch: master
        repo: 'https://github.com/Azure/azure-iot-sdk-java'
      path: provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/exceptions/ProvisioningServiceClientExceptionManager.java
      startLine: 12
    package: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    summary: <p>デバイスのプロビジョニング サービス結果を確認し、適切な例外をスローする静的関数を提供します。 </p>
    syntax:
      content: public class ProvisioningServiceClientExceptionManager
    inheritance:
      - java.lang.Object
  - uid: 'com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.httpResponseVerification(int,String)'
    id: 'httpResponseVerification(int,String)'
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.yml
    langs:
      - java
    name: 'httpResponseVerification(int responseStatus, String errorReason)'
    nameWithType: 'ProvisioningServiceClientExceptionManager.httpResponseVerification(int responseStatus, String errorReason)'
    fullName: 'static void com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientExceptionManager.httpResponseVerification(int responseStatus, String errorReason)'
    overload: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.httpResponseVerification*
    type: Method
    source:
      remote: *ref_0
      path: provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/exceptions/ProvisioningServiceClientExceptionManager.java
      startLine: 47
    package: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    summary: |-
      <p>応答状態を使用して応答を確認してください。</p>
      <p>

        <pre>

          <code>ProvisioningServiceClientServiceException [any exception reported in the http response]

              |

              |

              +--&gt;ProvisioningServiceClientBadUsageException [any http response 4xx]

              |        |

              |        +--&gt;ProvisioningServiceClientBadFormatException [400]

              |        +--&gt;ProvisioningServiceClientUnathorizedException [401]

              |        +--&gt;ProvisioningServiceClientNotFoundException [404]

              |        +--&gt;ProvisioningServiceClientPreconditionFailedException [412]

              |        +--&gt;ProvisioningServiceClientTooManyRequestsException [429]

              |

              +--&gt;ProvisioningServiceClientTransientException [any http response 5xx]

              |        |

              |        +--&gt;ProvisioningServiceClientInternalServerErrorException [500]

              |

              +--&gt;ProvisioningServiceClientUnknownException [any other http response &gt;300, but not 4xx or 5xx]

          </code>

        </pre>

      </p>
      <p></p>
    syntax:
      content: 'public static void httpResponseVerification(int responseStatus, String errorReason)'
      parameters:
        - id: responseStatus
          type: f75371fa
          description: <p>応答をステータスします。 </p>
        - id: errorReason
          type: '26831127'
          description: <p>エラーの説明です。 </p>
    exceptions:
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisec31e828069304f763e053102a181f40
        description: <p>応答状態 400 が等しい場合、この例外がスローされます。 </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis428e63329f7d8f9903aef432fc5a668d
        description: <p>応答状態 401 が等しい場合、この例外がスローされます。 </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis6cc9774bace2e6db41a3904df348eee0
        description: <p>応答状態 404 が等しい場合、この例外がスローされます。 </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf4a87e2786406409f327606adae377d
        description: <p>応答ステータス 412 が等しい場合、この例外がスローされます。 </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a4878881f4ac3e4806ac2bc0f67ca18
        description: <p>応答状態 500 が等しい場合、この例外がスローされます。 </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf54b54351d86c7bee42822d640658c9
        description: '<p>この例外がスローされます、応答ステータスの上にし、大きい 300 分の [なし] </p>'
references:
  - uid: f75371fa
    spec.java:
      - name: int
        fullName: int
  - uid: '26831127'
    spec.java:
      - name: String
        fullName: String
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.httpResponseVerification*
    name: httpResponseVerification
    nameWithType: ProvisioningServiceClientExceptionManager.httpResponseVerification
    fullName: static void com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientExceptionManager.httpResponseVerification
    package: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf54b54351d86c7bee42822d640658c9
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf54b54351d86c7bee42822d640658c9.yml
    name: ProvisioningServiceClientServiceException
    nameWithType: ProvisioningServiceClientServiceException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientServiceException
    type: Class
    summary: <p>これは、サービスによって報告された例外のデバイスのプロビジョニング サービス例外のサブセットです。 </p>
    syntax:
      content: public class ProvisioningServiceClientServiceException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisec31e828069304f763e053102a181f40
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisec31e828069304f763e053102a181f40.yml
    name: ProvisioningServiceClientBadFormatException
    nameWithType: ProvisioningServiceClientBadFormatException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientBadFormatException
    type: Class
    summary: |-
      <p>無効なメッセージ形式の例外を作成します。</p>
      <p>Http 要求の本文が正しくありません。たとえば、解析できないまたは、オブジェクトを検証することはできません。 </p>
      <p>HTTP ステータス コード 400 です。 </p>
    syntax:
      content: public class ProvisioningServiceClientBadFormatException extends ProvisioningServiceClientBadUsageException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis428e63329f7d8f9903aef432fc5a668d
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis428e63329f7d8f9903aef432fc5a668d.yml
    name: ProvisioningServiceClientUnathorizedException
    nameWithType: ProvisioningServiceClientUnathorizedException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientUnathorizedException
    type: Class
    summary: |-
      <p>承認されていない例外を作成します。</p>
      <p>認証トークンを検証することはできません。たとえば、有効期限が切れてや requestâ€ には適用されません™ s URI。 このエラー コードは、TPM の構成証明のフローの一部としてデバイスにも返されます。 </p>
      <p>HTTP ステータス コード 401 </p>
    syntax:
      content: public class ProvisioningServiceClientUnathorizedException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis6cc9774bace2e6db41a3904df348eee0
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis6cc9774bace2e6db41a3904df348eee0.yml
    name: ProvisioningServiceClientNotFoundException
    nameWithType: ProvisioningServiceClientNotFoundException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientNotFoundException
    type: Class
    summary: |-
      <p>例外が見つかりません。 デバイスのプロビジョニング サービスを作成します。</p>
      <p>デバイスのプロビジョニング サービス インスタンス、またはリソース (登録など) が存在しません。 </p>
      <p>HTTP ステータス コード 404。 </p>
    syntax:
      content: public class ProvisioningServiceClientNotFoundException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf4a87e2786406409f327606adae377d
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf4a87e2786406409f327606adae377d.yml
    name: ProvisioningServiceClientPreconditionFailedException
    nameWithType: ProvisioningServiceClientPreconditionFailedException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientPreconditionFailedException
    type: Class
    summary: |-
      <p>前提条件が失敗しました例外を作成します。</p>
      <p>要求内の ETag が RFC7232 に従って、既存のリソースの ETag と一致しません。 </p>
      <p>HTTP ステータス コード 412 です。 </p>
    syntax:
      content: public class ProvisioningServiceClientPreconditionFailedException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a4878881f4ac3e4806ac2bc0f67ca18
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a4878881f4ac3e4806ac2bc0f67ca18.yml
    name: ProvisioningServiceClientInternalServerErrorException
    nameWithType: ProvisioningServiceClientInternalServerErrorException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientInternalServerErrorException
    type: Class
    summary: |-
      <p>内部サーバー エラーの例外を作成します。</p>
      <p>内部エラーが発生しました。 </p>
      <p>HTTP 状態コード 500 です。 </p>
    syntax:
      content: public class ProvisioningServiceClientInternalServerErrorException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8d640264fa5997294ef7a61f3c9f7e67
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8d640264fa5997294ef7a61f3c9f7e67.yml
    name: ProvisioningServiceClientBadUsageException
    nameWithType: ProvisioningServiceClientBadUsageException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientBadUsageException
    type: Class
    summary: |-
      <p>これは、使用法エラーに関連する例外のデバイスのプロビジョニング サービス例外のサブセットです。</p>
      <p>プロビジョニング サービスが応答不適切な使用法は、例外のいずれかの http 要求、rest API が正しく呼び出された場合、使用状況の問題には、インスタンスのユーザーは、その操作の権限がありません。 </p>
      <p>HTTP ステータス コード 400 ~ 499 です。 </p>
    syntax:
      content: public class ProvisioningServiceClientBadUsageException extends ProvisioningServiceClientServiceException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a0fa33fb6d65f102e28e9bcde677ce1
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a0fa33fb6d65f102e28e9bcde677ce1.yml
    name: ProvisioningServiceClientTransientException
    nameWithType: ProvisioningServiceClientTransientException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientTransientException
    type: Class
    summary: |-
      <p>これは、例外が、一時的なサービスの問題を関連するデバイスのプロビジョニング サービス例外のサブセットです。</p>
      <p>プロビジョニング サービスは、rest API は、適切に呼び出されが、サービスがその時点でそのアクションを実行することではない場合に、一時的な例外のいずれかの http 要求になるように応答します。 これらは、再試行に役立つ、問題を解決する例外です。 </p>
      <p>HTTP 状態コード 500 を 599 です。 </p>
    syntax:
      content: public class ProvisioningServiceClientTransientException