### YamlMime:ManagedReference
items:
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615
    id: _provis0d423877466065f42d44d66a2d881615
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    children:
      - 'com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.httpResponseVerification(int,String)'
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.yml
    langs:
      - java
    name: ProvisioningServiceClientExceptionManager
    nameWithType: ProvisioningServiceClientExceptionManager
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientExceptionManager
    type: Class
    source:
      remote: &ref_0
        path: provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/exceptions/ProvisioningServiceClientExceptionManager.java
        branch: master
        repo: 'https://github.com/Azure/azure-iot-sdk-java'
      path: provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/exceptions/ProvisioningServiceClientExceptionManager.java
      startLine: 12
    package: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    summary: <p><span data-ttu-id="2bb2e-101">デバイスのプロビジョニング サービス結果を確認し、適切な例外をスローする静的関数を提供します。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-101">Provide static function to verify the Device Provisioning Service results and throw appropriate exception.</span></span> </p>
    syntax:
      content: public class ProvisioningServiceClientExceptionManager
    inheritance:
      - java.lang.Object
  - uid: 'com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.httpResponseVerification(int,String)'
    id: 'httpResponseVerification(int,String)'
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.yml
    langs:
      - java
    name: 'httpResponseVerification(int responseStatus, String errorReason)'
    nameWithType: 'ProvisioningServiceClientExceptionManager.httpResponseVerification(int responseStatus, String errorReason)'
    fullName: 'static void com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientExceptionManager.httpResponseVerification(int responseStatus, String errorReason)'
    overload: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.httpResponseVerification*
    type: Method
    source:
      remote: *ref_0
      path: provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/exceptions/ProvisioningServiceClientExceptionManager.java
      startLine: 47
    package: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    summary: |-
      <p><span data-ttu-id="2bb2e-102">応答状態を使用して応答を確認してください。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-102">Verify response using response status</span></span></p>
      <p>

        <pre>

          <code>ProvisioningServiceClientServiceException [any exception reported in the http response]

              |

              |

              +--&gt;ProvisioningServiceClientBadUsageException [any http response 4xx]

              |        |

              |        +--&gt;ProvisioningServiceClientBadFormatException [400]

              |        +--&gt;ProvisioningServiceClientUnathorizedException [401]

              |        +--&gt;ProvisioningServiceClientNotFoundException [404]

              |        +--&gt;ProvisioningServiceClientPreconditionFailedException [412]

              |        +--&gt;ProvisioningServiceClientTooManyRequestsException [429]

              |

              +--&gt;ProvisioningServiceClientTransientException [any http response 5xx]

              |        |

              |        +--&gt;ProvisioningServiceClientInternalServerErrorException [500]

              |

              +--&gt;ProvisioningServiceClientUnknownException [any other http response &gt;300, but not 4xx or 5xx]

          </code>

        </pre>

      </p>
      <p></p>
    syntax:
      content: 'public static void httpResponseVerification(int responseStatus, String errorReason)'
      parameters:
        - id: responseStatus
          type: f75371fa
          description: <p><span data-ttu-id="2bb2e-103">応答をステータスします。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-103">is the response status</span></span> </p>
        - id: errorReason
          type: '26831127'
          description: <p><span data-ttu-id="2bb2e-104">エラーの説明です。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-104">is the error description</span></span> </p>
    exceptions:
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisec31e828069304f763e053102a181f40
        description: <p><span data-ttu-id="2bb2e-105">応答状態 400 が等しい場合、この例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-105">This exception is thrown if the response status equal 400</span></span> </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis428e63329f7d8f9903aef432fc5a668d
        description: <p><span data-ttu-id="2bb2e-106">応答状態 401 が等しい場合、この例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-106">This exception is thrown if the response status equal 401</span></span> </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis6cc9774bace2e6db41a3904df348eee0
        description: <p><span data-ttu-id="2bb2e-107">応答状態 404 が等しい場合、この例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-107">This exception is thrown if the response status equal 404</span></span> </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf4a87e2786406409f327606adae377d
        description: <p><span data-ttu-id="2bb2e-108">応答ステータス 412 が等しい場合、この例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-108">This exception is thrown if the response status equal 412</span></span> </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a4878881f4ac3e4806ac2bc0f67ca18
        description: <p><span data-ttu-id="2bb2e-109">応答状態 500 が等しい場合、この例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-109">This exception is thrown if the response status equal 500</span></span> </p>
      - type: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf54b54351d86c7bee42822d640658c9
        description: '<p><span data-ttu-id="2bb2e-110">この例外がスローされます、応答ステータスの上にし、大きい 300 分の [なし]</span><span class="sxs-lookup"><span data-stu-id="2bb2e-110">This exception is thrown if the response status none of them above and greater then 300</span></span> </p>'
references:
  - uid: f75371fa
    spec.java:
      - name: int
        fullName: int
  - uid: '26831127'
    spec.java:
      - name: String
        fullName: String
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis0d423877466065f42d44d66a2d881615.httpResponseVerification*
    name: httpResponseVerification
    nameWithType: ProvisioningServiceClientExceptionManager.httpResponseVerification
    fullName: static void com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientExceptionManager.httpResponseVerification
    package: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf54b54351d86c7bee42822d640658c9
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf54b54351d86c7bee42822d640658c9.yml
    name: ProvisioningServiceClientServiceException
    nameWithType: ProvisioningServiceClientServiceException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientServiceException
    type: Class
    summary: <p><span data-ttu-id="2bb2e-111">これは、サービスによって報告された例外のデバイスのプロビジョニング サービス例外のサブセットです。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-111">This is the subset of the Device Provisioning Service exceptions for the exceptions reported by the Service.</span></span> </p>
    syntax:
      content: public class ProvisioningServiceClientServiceException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisec31e828069304f763e053102a181f40
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisec31e828069304f763e053102a181f40.yml
    name: ProvisioningServiceClientBadFormatException
    nameWithType: ProvisioningServiceClientBadFormatException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientBadFormatException
    type: Class
    summary: |-
      <p><span data-ttu-id="2bb2e-112">無効なメッセージ形式の例外を作成します。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-112">Create bad message format exception</span></span></p>
      <p><span data-ttu-id="2bb2e-113">Http 要求の本文が正しくありません。たとえば、解析できないまたは、オブジェクトを検証することはできません。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-113">The body of the Http request is not valid; for example, it cannot be parsed, or the object cannot be validated.</span></span> </p>
      <p><span data-ttu-id="2bb2e-114">HTTP ステータス コード 400 です。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-114">HTTP status code 400.</span></span> </p>
    syntax:
      content: public class ProvisioningServiceClientBadFormatException extends ProvisioningServiceClientBadUsageException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis428e63329f7d8f9903aef432fc5a668d
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis428e63329f7d8f9903aef432fc5a668d.yml
    name: ProvisioningServiceClientUnathorizedException
    nameWithType: ProvisioningServiceClientUnathorizedException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientUnathorizedException
    type: Class
    summary: |-
      <p><span data-ttu-id="2bb2e-115">承認されていない例外を作成します。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-115">Create unauthorized exception</span></span></p>
      <p><span data-ttu-id="2bb2e-116">認証トークンを検証することはできません。たとえば、有効期限が切れてや requestâ€ には適用されません™ s URI。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-116">The authorization token cannot be validated; for example, it is expired or does not apply to the requestâ€™s URI.</span></span> <span data-ttu-id="2bb2e-117">このエラー コードは、TPM の構成証明のフローの一部としてデバイスにも返されます。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-117">This error code is also returned to devices as part of the TPM attestation flow.</span></span> </p>
      <p><span data-ttu-id="2bb2e-118">HTTP ステータス コード 401</span><span class="sxs-lookup"><span data-stu-id="2bb2e-118">HTTP status code 401</span></span> </p>
    syntax:
      content: public class ProvisioningServiceClientUnathorizedException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis6cc9774bace2e6db41a3904df348eee0
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis6cc9774bace2e6db41a3904df348eee0.yml
    name: ProvisioningServiceClientNotFoundException
    nameWithType: ProvisioningServiceClientNotFoundException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientNotFoundException
    type: Class
    summary: |-
      <p><span data-ttu-id="2bb2e-119">例外が見つかりません。 デバイスのプロビジョニング サービスを作成します。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-119">Create Device Provisioning Service not found exception</span></span></p>
      <p><span data-ttu-id="2bb2e-120">デバイスのプロビジョニング サービス インスタンス、またはリソース (登録など) が存在しません。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-120">The Device Provisioning Service instance, or a resource (e.g. an enrollment) does not exist.</span></span> </p>
      <p><span data-ttu-id="2bb2e-121">HTTP ステータス コード 404。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-121">HTTP status code 404.</span></span> </p>
    syntax:
      content: public class ProvisioningServiceClientNotFoundException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf4a87e2786406409f327606adae377d
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provisdf4a87e2786406409f327606adae377d.yml
    name: ProvisioningServiceClientPreconditionFailedException
    nameWithType: ProvisioningServiceClientPreconditionFailedException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientPreconditionFailedException
    type: Class
    summary: |-
      <p><span data-ttu-id="2bb2e-122">前提条件が失敗しました例外を作成します。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-122">Create precondition failed exception</span></span></p>
      <p><span data-ttu-id="2bb2e-123">要求内の ETag が RFC7232 に従って、既存のリソースの ETag と一致しません。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-123">The ETag in the request does not match the ETag of the existing resource, as per RFC7232.</span></span> </p>
      <p><span data-ttu-id="2bb2e-124">HTTP ステータス コード 412 です。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-124">HTTP status code 412.</span></span> </p>
    syntax:
      content: public class ProvisioningServiceClientPreconditionFailedException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a4878881f4ac3e4806ac2bc0f67ca18
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a4878881f4ac3e4806ac2bc0f67ca18.yml
    name: ProvisioningServiceClientInternalServerErrorException
    nameWithType: ProvisioningServiceClientInternalServerErrorException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientInternalServerErrorException
    type: Class
    summary: |-
      <p><span data-ttu-id="2bb2e-125">内部サーバー エラーの例外を作成します。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-125">Create internal server error exception</span></span></p>
      <p><span data-ttu-id="2bb2e-126">内部エラーが発生しました。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-126">An internal error occurred.</span></span> </p>
      <p><span data-ttu-id="2bb2e-127">HTTP 状態コード 500 です。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-127">HTTP status code 500.</span></span> </p>
    syntax:
      content: public class ProvisioningServiceClientInternalServerErrorException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8d640264fa5997294ef7a61f3c9f7e67
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8d640264fa5997294ef7a61f3c9f7e67.yml
    name: ProvisioningServiceClientBadUsageException
    nameWithType: ProvisioningServiceClientBadUsageException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientBadUsageException
    type: Class
    summary: |-
      <p><span data-ttu-id="2bb2e-128">これは、使用法エラーに関連する例外のデバイスのプロビジョニング サービス例外のサブセットです。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-128">This is the subset of the Device Provisioning Service exceptions for the exceptions related to usage error.</span></span></p>
      <p><span data-ttu-id="2bb2e-129">プロビジョニング サービスが応答不適切な使用法は、例外のいずれかの http 要求、rest API が正しく呼び出された場合、使用状況の問題には、インスタンスのユーザーは、その操作の権限がありません。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-129">The provisioning service will response a http request with one of the bad usage exception if the rest API was properly called, with a usage issue, for instance the user is not authorized for that operation.</span></span> </p>
      <p><span data-ttu-id="2bb2e-130">HTTP ステータス コード 400 ~ 499 です。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-130">HTTP status code 400 to 499.</span></span> </p>
    syntax:
      content: public class ProvisioningServiceClientBadUsageException extends ProvisioningServiceClientServiceException
  - uid: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a0fa33fb6d65f102e28e9bcde677ce1
    parent: com.microsoft.azure.sdk.iot.provisioning.service.exceptions
    href: com.microsoft.azure.sdk.iot.provisioning.service.exceptions._provis8a0fa33fb6d65f102e28e9bcde677ce1.yml
    name: ProvisioningServiceClientTransientException
    nameWithType: ProvisioningServiceClientTransientException
    fullName: com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientTransientException
    type: Class
    summary: |-
      <p><span data-ttu-id="2bb2e-131">これは、例外が、一時的なサービスの問題を関連するデバイスのプロビジョニング サービス例外のサブセットです。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-131">This is the subset of the Device Provisioning Service exceptions for the exceptions related a temporary service issue.</span></span></p>
      <p><span data-ttu-id="2bb2e-132">プロビジョニング サービスは、rest API は、適切に呼び出されが、サービスがその時点でそのアクションを実行することではない場合に、一時的な例外のいずれかの http 要求になるように応答します。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-132">The provisioning service will response a http request with one of the transient exception if the rest API was properly called, but the service is not able to execute that action at that time.</span></span> <span data-ttu-id="2bb2e-133">これらは、再試行に役立つ、問題を解決する例外です。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-133">These are the exceptions that a retry can help to fix the issue.</span></span> </p>
      <p><span data-ttu-id="2bb2e-134">HTTP 状態コード 500 を 599 です。</span><span class="sxs-lookup"><span data-stu-id="2bb2e-134">HTTP status code 500 to 599.</span></span> </p>
    syntax:
      content: public class ProvisioningServiceClientTransientException