### YamlMime:ManagedReference
items:
  - uid: com.microsoft.azure.eventhubs._event_hub_exception
    id: _event_hub_exception
    parent: com.microsoft.azure.eventhubs
    children:
      - 'com.microsoft.azure.eventhubs._event_hub_exception.EventHubException(final boolean,final String)'
      - 'com.microsoft.azure.eventhubs._event_hub_exception.EventHubException(final boolean,final String,final Throwable)'
      - 'com.microsoft.azure.eventhubs._event_hub_exception.EventHubException(final boolean,final Throwable)'
      - com.microsoft.azure.eventhubs._event_hub_exception.getContext()
      - com.microsoft.azure.eventhubs._event_hub_exception.getIsTransient()
      - com.microsoft.azure.eventhubs._event_hub_exception.getMessage()
    href: com.microsoft.azure.eventhubs._event_hub_exception.yml
    langs:
      - java
    name: EventHubException
    nameWithType: EventHubException
    fullName: com.microsoft.azure.eventhubs.EventHubException
    type: Class
    source:
      remote: &ref_0
        path: azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubException.java
        branch: master
        repo: 'https://github.com/Azure/azure-event-hubs-java'
      path: azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubException.java
      startLine: 11
    package: com.microsoft.azure.eventhubs
    summary: <p><span data-ttu-id="f1ce5-101">これは、基本例外をサービス バスは、すべてのエラー ケースを生成します。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-101">This is the base exception that service bus will produce for all error cases.</span></span> </p>
    syntax:
      content: public class EventHubException
    inheritance:
      - java.lang.Object
      - Exception
  - uid: 'com.microsoft.azure.eventhubs._event_hub_exception.EventHubException(final boolean,final String)'
    id: 'EventHubException(final boolean,final String)'
    parent: com.microsoft.azure.eventhubs._event_hub_exception
    href: com.microsoft.azure.eventhubs._event_hub_exception.yml
    langs:
      - java
    name: 'EventHubException(final boolean isTransient, final String message)'
    nameWithType: 'EventHubException.EventHubException(final boolean isTransient, final String message)'
    fullName: 'com.microsoft.azure.eventhubs.EventHubException.EventHubException(final boolean isTransient, final String message)'
    overload: com.microsoft.azure.eventhubs._event_hub_exception.EventHubException*
    type: Constructor
    source:
      remote: *ref_0
      path: azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubException.java
      startLine: 24
    package: com.microsoft.azure.eventhubs
    syntax:
      content: 'public EventHubException(final boolean isTransient, final String message)'
      parameters:
        - id: isTransient
          type: 4dda0764
        - id: message
          type: 3d93591e
  - uid: 'com.microsoft.azure.eventhubs._event_hub_exception.EventHubException(final boolean,final String,final Throwable)'
    id: 'EventHubException(final boolean,final String,final Throwable)'
    parent: com.microsoft.azure.eventhubs._event_hub_exception
    href: com.microsoft.azure.eventhubs._event_hub_exception.yml
    langs:
      - java
    name: 'EventHubException(final boolean isTransient, final String message, final Throwable cause)'
    nameWithType: 'EventHubException.EventHubException(final boolean isTransient, final String message, final Throwable cause)'
    fullName: 'com.microsoft.azure.eventhubs.EventHubException.EventHubException(final boolean isTransient, final String message, final Throwable cause)'
    overload: com.microsoft.azure.eventhubs._event_hub_exception.EventHubException*
    type: Constructor
    source:
      remote: *ref_0
      path: azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubException.java
      startLine: 36
    package: com.microsoft.azure.eventhubs
    syntax:
      content: 'public EventHubException(final boolean isTransient, final String message, final Throwable cause)'
      parameters:
        - id: isTransient
          type: 4dda0764
        - id: message
          type: 3d93591e
        - id: cause
          type: fa00b19f
  - uid: 'com.microsoft.azure.eventhubs._event_hub_exception.EventHubException(final boolean,final Throwable)'
    id: 'EventHubException(final boolean,final Throwable)'
    parent: com.microsoft.azure.eventhubs._event_hub_exception
    href: com.microsoft.azure.eventhubs._event_hub_exception.yml
    langs:
      - java
    name: 'EventHubException(final boolean isTransient, final Throwable cause)'
    nameWithType: 'EventHubException.EventHubException(final boolean isTransient, final Throwable cause)'
    fullName: 'com.microsoft.azure.eventhubs.EventHubException.EventHubException(final boolean isTransient, final Throwable cause)'
    overload: com.microsoft.azure.eventhubs._event_hub_exception.EventHubException*
    type: Constructor
    source:
      remote: *ref_0
      path: azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubException.java
      startLine: 30
    package: com.microsoft.azure.eventhubs
    syntax:
      content: 'public EventHubException(final boolean isTransient, final Throwable cause)'
      parameters:
        - id: isTransient
          type: 4dda0764
        - id: cause
          type: fa00b19f
  - uid: com.microsoft.azure.eventhubs._event_hub_exception.getContext()
    id: getContext()
    parent: com.microsoft.azure.eventhubs._event_hub_exception
    href: com.microsoft.azure.eventhubs._event_hub_exception.yml
    langs:
      - java
    name: getContext()
    nameWithType: EventHubException.getContext()
    fullName: ErrorContext com.microsoft.azure.eventhubs.EventHubException.getContext()
    overload: com.microsoft.azure.eventhubs._event_hub_exception.getContext*
    type: Method
    source:
      remote: *ref_0
      path: azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubException.java
      startLine: 62
    package: com.microsoft.azure.eventhubs
    syntax:
      content: public ErrorContext getContext()
      return:
        type: com.microsoft.azure.eventhubs._error_context
  - uid: com.microsoft.azure.eventhubs._event_hub_exception.getIsTransient()
    id: getIsTransient()
    parent: com.microsoft.azure.eventhubs._event_hub_exception
    href: com.microsoft.azure.eventhubs._event_hub_exception.yml
    langs:
      - java
    name: getIsTransient()
    nameWithType: EventHubException.getIsTransient()
    fullName: boolean com.microsoft.azure.eventhubs.EventHubException.getIsTransient()
    overload: com.microsoft.azure.eventhubs._event_hub_exception.getIsTransient*
    type: Method
    source:
      remote: *ref_0
      path: azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubException.java
      startLine: 57
    package: com.microsoft.azure.eventhubs
    summary: <p><span data-ttu-id="f1ce5-102">例外が、一時的なエラーかを示すブール値。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-102">A boolean indicating if the exception is a transient error or not.</span></span> </p>
    syntax:
      content: public boolean getIsTransient()
      return:
        type: 4fc6e284
        description: <p><span data-ttu-id="f1ce5-103">ユーザーがその他の介入なし例外を生成した操作を再試行できる場合に true を返します。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-103">returns true when user can retry the operation that generated the exception without additional intervention.</span></span> </p>
  - uid: com.microsoft.azure.eventhubs._event_hub_exception.getMessage()
    id: getMessage()
    parent: com.microsoft.azure.eventhubs._event_hub_exception
    href: com.microsoft.azure.eventhubs._event_hub_exception.yml
    langs:
      - java
    name: getMessage()
    nameWithType: EventHubException.getMessage()
    fullName: String com.microsoft.azure.eventhubs.EventHubException.getMessage()
    overload: com.microsoft.azure.eventhubs._event_hub_exception.getMessage*
    type: Method
    source:
      remote: *ref_0
      path: azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubException.java
      startLine: 43
    package: com.microsoft.azure.eventhubs
    syntax:
      content: public String getMessage()
      return:
        type: '26831127'
references:
  - uid: 4dda0764
    spec.java:
      - name: final boolean
        fullName: final boolean
  - uid: 3d93591e
    spec.java:
      - name: final String
        fullName: final String
  - uid: com.microsoft.azure.eventhubs._event_hub_exception.EventHubException*
    name: EventHubException
    nameWithType: EventHubException.EventHubException
    fullName: com.microsoft.azure.eventhubs.EventHubException.EventHubException
    package: com.microsoft.azure.eventhubs
  - uid: fa00b19f
    spec.java:
      - name: final Throwable
        fullName: final Throwable
  - uid: '26831127'
    spec.java:
      - name: String
        fullName: String
  - uid: com.microsoft.azure.eventhubs._event_hub_exception.getMessage*
    name: getMessage
    nameWithType: EventHubException.getMessage
    fullName: String com.microsoft.azure.eventhubs.EventHubException.getMessage
    package: com.microsoft.azure.eventhubs
  - uid: 4fc6e284
    spec.java:
      - name: boolean
        fullName: boolean
  - uid: com.microsoft.azure.eventhubs._event_hub_exception.getIsTransient*
    name: getIsTransient
    nameWithType: EventHubException.getIsTransient
    fullName: boolean com.microsoft.azure.eventhubs.EventHubException.getIsTransient
    package: com.microsoft.azure.eventhubs
  - uid: com.microsoft.azure.eventhubs._event_hub_exception.getContext*
    name: getContext
    nameWithType: EventHubException.getContext
    fullName: ErrorContext com.microsoft.azure.eventhubs.EventHubException.getContext
    package: com.microsoft.azure.eventhubs
  - uid: com.microsoft.azure.eventhubs._authorization_failed_exception
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._authorization_failed_exception.yml
    name: AuthorizationFailedException
    nameWithType: AuthorizationFailedException
    fullName: com.microsoft.azure.eventhubs.AuthorizationFailedException
    type: Class
    summary: |-
      <p><span data-ttu-id="f1ce5-104">承認が目的の操作を実行するユーザーのアクセス許可の承認中にエラーが発生した場合に障害が発生した例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-104">Authorization failed exception is thrown when error is encountered during authorizing user's permission to run the intended operations.</span></span> <span data-ttu-id="f1ce5-105">この例外が発生したときにユーザーが接続文字列でトークンまたはキーが提供されるかどうかを確認する必要があります (例: いずれかに渡す<xref uid="com.microsoft.azure.eventhubs._event_hub_client.createFromConnectionString(final String)" data-throw-if-not-resolved="false">com.microsoft.azure.eventhubs.EventHubClient#createFromConnectionString(String)</xref>) 有効ですが、あり (受信呼び出しなどが必要なリッスン キーまたはトークンに関連付けられた要求)、目的の操作の権利を正しく実行されます。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-105">When encountered this exception user should check whether the token/key provided in the connection string (e.g. one passed to <xref uid="com.microsoft.azure.eventhubs._event_hub_client.createFromConnectionString(final String)" data-throw-if-not-resolved="false">com.microsoft.azure.eventhubs.EventHubClient#createFromConnectionString(String)</xref>) is valid, and has correct execution right for the intended operations (e.g. Receive call will need Listen claim associated with the key/token).</span></span></p>
      <p></p>
    syntax:
      content: public class AuthorizationFailedException extends EventHubException
  - uid: com.microsoft.azure.eventhubs._communication_exception
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._communication_exception.yml
    name: CommunicationException
    nameWithType: CommunicationException
    fullName: com.microsoft.azure.eventhubs.CommunicationException
    type: Class
    summary: |-
      <p><span data-ttu-id="f1ce5-106">クライアント側の接続に問題がある場合は、この例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-106">This exception is thrown when there is a client side connectivity issue.</span></span> <span data-ttu-id="f1ce5-107">ときにこの例外のユーザーの受信は、サービスにクライアント接続設定を確認する必要があります。<itemizedlist><listitem></span><span class="sxs-lookup"><span data-stu-id="f1ce5-107">When receiving this exception user should check client connectivity settings to the service: <itemizedlist><listitem></span></span><p><span data-ttu-id="f1ce5-108">正しいホスト名およびエンドポイントで使用されるポート番号を確認します。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-108">Check for correct hostname and port number used in endpoint.</span></span> </p></listitem><listitem><p><span data-ttu-id="f1ce5-109">Amqp ポートをブロックするすべての可能なプロキシ設定を確認します。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-109">Check for any possible proxy settings that can block amqp ports</span></span> </p></listitem><listitem><p><span data-ttu-id="f1ce5-110">Amqp ポートをブロックするファイアウォールの設定の確認します。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-110">Check for any firewall settings that can block amqp ports</span></span> </p></listitem><listitem><p><span data-ttu-id="f1ce5-111">一般的なネットワーク接続の問題と、ネットワークの待機時間を確認します。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-111">Check for any general network connectivity issues, as well as network latency.</span></span> </p></listitem></itemizedlist></p>
      <p></p>
    syntax:
      content: public class CommunicationException extends EventHubException
  - uid: com.microsoft.azure.eventhubs._illegal_entity_exception
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._illegal_entity_exception.yml
    name: IllegalEntityException
    nameWithType: IllegalEntityException
    fullName: com.microsoft.azure.eventhubs.IllegalEntityException
    type: Class
    summary: |-
      <p><span data-ttu-id="f1ce5-112">この例外は、次の理由。<itemizedlist><listitem></span><span class="sxs-lookup"><span data-stu-id="f1ce5-112">This exception is thrown for the following reasons: <itemizedlist><listitem></span></span><p><span data-ttu-id="f1ce5-113">エンティティ ユーザーが接続しようとしたときに存在しません</span><span class="sxs-lookup"><span data-stu-id="f1ce5-113">When the entity user attempted to connect does not exist</span></span> </p></listitem><listitem><p><span data-ttu-id="f1ce5-114">接続するエンティティのユーザーが本人が無効になっています</span><span class="sxs-lookup"><span data-stu-id="f1ce5-114">The entity user wants to connect is disabled</span></span> </p></listitem></itemizedlist></p>
      <p></p>
    syntax:
      content: public class IllegalEntityException
  - uid: com.microsoft.azure.eventhubs._operation_cancelled_exception
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._operation_cancelled_exception.yml
    name: OperationCancelledException
    nameWithType: OperationCancelledException
    fullName: com.microsoft.azure.eventhubs.OperationCancelledException
    type: Class
    summary: <p><span data-ttu-id="f1ce5-115">この例外は、基になる Amqp 層が異常なリンクを検出すると、中止または予期しない方法で接続の切断します。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-115">This exception is thrown when the underlying Amqp layer encounter an abnormal link abort or disconnect of connection in an unexpected fashion.</span></span> </p>
    syntax:
      content: public class OperationCancelledException
  - uid: com.microsoft.azure.eventhubs._payload_size_exceeded_exception
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._payload_size_exceeded_exception.yml
    name: PayloadSizeExceededException
    nameWithType: PayloadSizeExceededException
    fullName: com.microsoft.azure.eventhubs.PayloadSizeExceededException
    type: Class
    summary: |-
      <p><span data-ttu-id="f1ce5-116">ユーザーが、イベント データやサービスによって定義されている許可されたペイロードのサイズを超えました仲介型メッセージを送信しようとした場合、この例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-116">this exception is thrown when user attempts to send a event data or brokered message that has exceeded the allowed payload size as defined by the service.</span></span> <span data-ttu-id="f1ce5-117">注バッチのシナリオに制限を送信するには、可能なバッチのオーバーヘッドを含めることができます。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-117">Note that in a batch send scenario the limit can include possible batch overhead.</span></span></p>
      <p></p>
    syntax:
      content: public class PayloadSizeExceededException
  - uid: com.microsoft.azure.eventhubs._quota_exceeded_exception
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._quota_exceeded_exception.yml
    name: QuotaExceededException
    nameWithType: QuotaExceededException
    fullName: com.microsoft.azure.eventhubs.QuotaExceededException
    type: Class
    syntax:
      content: public class QuotaExceededException
  - uid: com.microsoft.azure.eventhubs._receiver_disconnected_exception
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._receiver_disconnected_exception.yml
    name: ReceiverDisconnectedException
    nameWithType: ReceiverDisconnectedException
    fullName: com.microsoft.azure.eventhubs.ReceiverDisconnectedException
    type: Class
    summary: |-
      <p><span data-ttu-id="f1ce5-118">次の理由のいずれかの理由、EventHubReceiver は接続が切断されるときに、この例外がスローされます。<itemizedlist><listitem></span><span class="sxs-lookup"><span data-stu-id="f1ce5-118">This exception is thrown when a EventHubReceiver is being disconnected because of one of the following reason: <itemizedlist><listitem></span></span><p><span data-ttu-id="f1ce5-119">エポック レシーバーがある場合に、イベント ハブ パーティションに非エポック レシーバーを接続するユーザーの試行は、パーティションに接続します。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-119">user attempts to connect a non-epoch receiver to a event hub partition, when there is an epoch receiver connected to the partition.</span></span> </p></listitem><listitem><p><span data-ttu-id="f1ce5-120">エポック受信者を特定のパーティションを使用しているより高いエポック値を持つ別のエポック受信アダプターが同じパーティションに接続します。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-120">you are using an epoch receiver for a given partition but another epoch receiver with a higher epoch value connects to the same partition.</span></span> </p><span data-ttu-id="f1ce5-121"></listitem></itemizedlist>ユーザーは、か、すべてのコード非エポック受信機を使用している 1 つだけのエポック受信機が時間内の任意の時点で、特定のパーティションの処理があることを確認することを確認してください。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-121"></listitem></itemizedlist> User should make sure either all code are using non-epoch receivers, or ensure that there is only one epoch receiver processing a given partition at any given point in time.</span></span></p>
      <p></p>
    syntax:
      content: public class ReceiverDisconnectedException
  - uid: com.microsoft.azure.eventhubs._server_busy_exception
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._server_busy_exception.yml
    name: ServerBusyException
    nameWithType: ServerBusyException
    fullName: com.microsoft.azure.eventhubs.ServerBusyException
    type: Class
    summary: |-
      <p><span data-ttu-id="f1ce5-122">現在のエンティティのアクティビティがサービスに過剰な負荷を挿入がサーバーのビジー状態である例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-122">Server busy exception is thrown when the current entity's activity has put excessive load onto the service.</span></span> <span data-ttu-id="f1ce5-123">この例外が発生したときにユーザーとエンティティの再試行、および実行時の操作は、もう一度の前に、少なくとも 4 秒を待機する必要があります。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-123">When encountered this exception user should wait at least 4 seconds before any retry/runtime operations for the said entity again.</span></span></p>
      <p></p>
    syntax:
      content: public class ServerBusyException
  - uid: com.microsoft.azure.eventhubs._timeout_exception
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._timeout_exception.yml
    name: TimeoutException
    nameWithType: TimeoutException
    fullName: com.microsoft.azure.eventhubs.TimeoutException
    type: Class
    summary: |-
      <p><span data-ttu-id="f1ce5-124">操作があらかじめ設定された時間制限を超えたときに、この例外がスローされます。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-124">This exception is thrown when the operation has exceeded the predetermined time limit.</span></span> <span data-ttu-id="f1ce5-125">ユーザーは、接続はクライアント プロセスとサービス間で正常を確認する必要があります。</span><span class="sxs-lookup"><span data-stu-id="f1ce5-125">User should check connectivity is healthy between client process and service.</span></span></p>
      <p></p>
    syntax:
      content: public class TimeoutException
  - uid: com.microsoft.azure.eventhubs._error_context
    parent: com.microsoft.azure.eventhubs
    href: com.microsoft.azure.eventhubs._error_context.yml
    name: ErrorContext
    nameWithType: ErrorContext
    fullName: com.microsoft.azure.eventhubs.ErrorContext
    type: Class
    syntax:
      content: public class ErrorContext