### YamlMime:ManagedReference
items:
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    id: _multi_shard_result_set_internal_exception
    parent: com.microsoft.azure.elasticdb.query.exception
    children:
      - com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException()
      - com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException(String)
      - 'com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException(String,RuntimeException)'
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    langs:
      - java
    name: MultiShardResultSetInternalException
    nameWithType: MultiShardResultSetInternalException
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException
    type: Class
    source:
      remote: &ref_0
        path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
        branch: master
        repo: 'https://github.com/Microsoft/elastic-db-tools-for-java'
      path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
      startLine: 17
    package: com.microsoft.azure.elasticdb.query.exception
    summary: '<p><span data-ttu-id="48777-101">MultiShardResultSet が無効な状態のときにスローされるカスタムの例外。</span><span class="sxs-lookup"><span data-stu-id="48777-101">Custom exception that is thrown when the MultiShardResultSet is in an invalid state.</span></span> <span data-ttu-id="48777-102">この例外を繰り返し発生する場合、マイクロソフト カスタマー サポートにお問い合わせください。</span><span class="sxs-lookup"><span data-stu-id="48777-102">If you experience this exception repeatedly, please contact Microsoft Customer Support.</span></span> <span data-ttu-id="48777-103">目的: MultiShardResultSet が無効な状態のときにスローする例外をカスタムです。</span><span class="sxs-lookup"><span data-stu-id="48777-103">Purpose: Custom exception to throw when the MultiShardResultSet is in an invalid state.</span></span> <span data-ttu-id="48777-104">このエラーをしないように、ユーザー。</span><span class="sxs-lookup"><span data-stu-id="48777-104">This error should not make it out to the user.</span></span> </p>'
    syntax: &ref_1
      content: public class MultiShardResultSetInternalException
    inheritance:
      - java.lang.Object
      - RuntimeException
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException()
    id: MultiShardResultSetInternalException()
    parent: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    langs:
      - java
    name: MultiShardResultSetInternalException()
    nameWithType: MultiShardResultSetInternalException.MultiShardResultSetInternalException()
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException.MultiShardResultSetInternalException()
    overload: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException*
    type: Constructor
    source:
      remote: *ref_0
      path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
      startLine: 22
    package: com.microsoft.azure.elasticdb.query.exception
    summary: <p><span data-ttu-id="48777-105">新しいインスタンスを初期化、 <xref uid="com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception" data-throw-if-not-resolved="false">MultiShardResultSetInternalException</xref>クラスです。</span><span class="sxs-lookup"><span data-stu-id="48777-105">Initializes a new instance of the <xref uid="com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception" data-throw-if-not-resolved="false">MultiShardResultSetInternalException</xref> class.</span></span> </p>
    syntax:
      content: public MultiShardResultSetInternalException()
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException(String)
    id: MultiShardResultSetInternalException(String)
    parent: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    langs:
      - java
    name: MultiShardResultSetInternalException(String message)
    nameWithType: MultiShardResultSetInternalException.MultiShardResultSetInternalException(String message)
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException.MultiShardResultSetInternalException(String message)
    overload: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException*
    type: Constructor
    source:
      remote: *ref_0
      path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
      startLine: 32
    package: com.microsoft.azure.elasticdb.query.exception
    summary: |-
      <p><span data-ttu-id="48777-106">新しいインスタンスを初期化、 <xref uid="com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception" data-throw-if-not-resolved="false">MultiShardResultSetInternalException</xref>指定したエラー メッセージを使用します。</span><span class="sxs-lookup"><span data-stu-id="48777-106">Initializes a new instance of the <xref uid="com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception" data-throw-if-not-resolved="false">MultiShardResultSetInternalException</xref> class with a specified error message.</span></span></p>
      <p></p>
    syntax:
      content: public MultiShardResultSetInternalException(String message)
      parameters:
        - id: message
          type: '26831127'
          description: <p><span data-ttu-id="48777-107">エラーを説明するメッセージ。</span><span class="sxs-lookup"><span data-stu-id="48777-107">The message that describes the error.</span></span> </p>
  - uid: 'com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException(String,RuntimeException)'
    id: 'MultiShardResultSetInternalException(String,RuntimeException)'
    parent: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    langs:
      - java
    name: 'MultiShardResultSetInternalException(String message, RuntimeException innerException)'
    nameWithType: 'MultiShardResultSetInternalException.MultiShardResultSetInternalException(String message, RuntimeException innerException)'
    fullName: 'com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException.MultiShardResultSetInternalException(String message, RuntimeException innerException)'
    overload: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException*
    type: Constructor
    source:
      remote: *ref_0
      path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
      startLine: 44
    package: com.microsoft.azure.elasticdb.query.exception
    summary: |-
      <p><span data-ttu-id="48777-108">新しいインスタンスを初期化、 <xref uid="com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception" data-throw-if-not-resolved="false">MultiShardResultSetInternalException</xref>メッセージと内部例外を持つクラス。</span><span class="sxs-lookup"><span data-stu-id="48777-108">Initializes a new instance of the <xref uid="com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception" data-throw-if-not-resolved="false">MultiShardResultSetInternalException</xref> class with a message and an inner exception.</span></span></p>
      <p></p>
    syntax:
      content: 'public MultiShardResultSetInternalException(String message, RuntimeException innerException)'
      parameters:
        - id: message
          type: '26831127'
          description: <p><span data-ttu-id="48777-109">例外でカプセル化するメッセージ。</span><span class="sxs-lookup"><span data-stu-id="48777-109">The message to encapsulate in the exception.</span></span> </p>
        - id: innerException
          type: 9b2a4515
          description: <p><span data-ttu-id="48777-110">この例外の原因となる基になる例外。</span><span class="sxs-lookup"><span data-stu-id="48777-110">The underlying exception that causes this exception.</span></span> </p>
references:
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException*
    name: MultiShardResultSetInternalException
    nameWithType: MultiShardResultSetInternalException.MultiShardResultSetInternalException
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException.MultiShardResultSetInternalException
    package: com.microsoft.azure.elasticdb.query.exception
  - uid: '26831127'
    spec.java:
      - name: String
        fullName: String
  - uid: 9b2a4515
    spec.java:
      - name: RuntimeException
        fullName: RuntimeException
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    parent: com.microsoft.azure.elasticdb.query.exception
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    name: MultiShardResultSetInternalException
    nameWithType: MultiShardResultSetInternalException
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException
    type: Class
    summary: '<p><span data-ttu-id="48777-111">MultiShardResultSet が無効な状態のときにスローされるカスタムの例外。</span><span class="sxs-lookup"><span data-stu-id="48777-111">Custom exception that is thrown when the MultiShardResultSet is in an invalid state.</span></span> <span data-ttu-id="48777-112">この例外を繰り返し発生する場合、マイクロソフト カスタマー サポートにお問い合わせください。</span><span class="sxs-lookup"><span data-stu-id="48777-112">If you experience this exception repeatedly, please contact Microsoft Customer Support.</span></span> <span data-ttu-id="48777-113">目的: MultiShardResultSet が無効な状態のときにスローする例外をカスタムです。</span><span class="sxs-lookup"><span data-stu-id="48777-113">Purpose: Custom exception to throw when the MultiShardResultSet is in an invalid state.</span></span> <span data-ttu-id="48777-114">このエラーをしないように、ユーザー。</span><span class="sxs-lookup"><span data-stu-id="48777-114">This error should not make it out to the user.</span></span> </p>'
    syntax: *ref_1