### YamlMime:ManagedReference
items:
  - uid: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception
    id: _reentrancy_mode_disallowed_exception
    parent: microsoft.servicefabric.actors
    children:
      - microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException()
      - microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException(String)
      - 'microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException(String,Throwable)'
      - 'microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException(String,Throwable,boolean,boolean)'
      - microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException(Throwable)
    href: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.yml
    langs:
      - java
    name: ReentrancyModeDisallowedException
    nameWithType: ReentrancyModeDisallowedException
    fullName: microsoft.servicefabric.actors.ReentrancyModeDisallowedException
    type: Class
    source:
      remote: &ref_0
        path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ReentrancyModeDisallowedException.java
        branch: master
        repo: 'https://msazure.visualstudio.com/One/_git/sf-java'
      path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ReentrancyModeDisallowedException.java
      startLine: 8
    package: microsoft.servicefabric.actors
    summary: '<p>アクターの再入可能呼び出しが行われたときにアクター ランタイムによってスローされる例外とその<xref uid="microsoft.servicefabric.actors._reentrancy_mode" data-throw-if-not-resolved="false">ReentrancyMode</xref>に設定されている<xref uid="microsoft.servicefabric.actors._reentrancy_mode.Disallowed" data-throw-if-not-resolved="false">ReentrancyMode #Disallowed</xref>です。 </p>'
    syntax: &ref_1
      content: public class ReentrancyModeDisallowedException extends FabricException
    inheritance:
      - java.lang.Object
      - RuntimeException
      - system.fabric.exception._fabric_exception
    inheritedMembers:
      - system.fabric.exception._fabric_exception.FabricException()
      - system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
      - system.fabric.exception._fabric_exception.FabricException(String)
      - 'system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)'
      - system.fabric.exception._fabric_exception.FabricException(Throwable)
      - 'system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)'
      - system.fabric.exception._fabric_exception.getErrorCode()
  - uid: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException()
    id: ReentrancyModeDisallowedException()
    parent: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception
    href: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.yml
    langs:
      - java
    name: ReentrancyModeDisallowedException()
    nameWithType: ReentrancyModeDisallowedException.ReentrancyModeDisallowedException()
    fullName: microsoft.servicefabric.actors.ReentrancyModeDisallowedException.ReentrancyModeDisallowedException()
    overload: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ReentrancyModeDisallowedException.java
      startLine: 16
    package: microsoft.servicefabric.actors
    summary: <p>新しいインスタンスを初期化、 <xref uid="microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception" data-throw-if-not-resolved="false">ReentrancyModeDisallowedException</xref>クラスです。 </p>
    syntax:
      content: public ReentrancyModeDisallowedException()
  - uid: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException(String)
    id: ReentrancyModeDisallowedException(String)
    parent: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception
    href: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.yml
    langs:
      - java
    name: ReentrancyModeDisallowedException(String message)
    nameWithType: ReentrancyModeDisallowedException.ReentrancyModeDisallowedException(String message)
    fullName: microsoft.servicefabric.actors.ReentrancyModeDisallowedException.ReentrancyModeDisallowedException(String message)
    overload: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ReentrancyModeDisallowedException.java
      startLine: 42
    package: microsoft.servicefabric.actors
    summary: |-
      <p>新しいインスタンスを初期化、 <xref uid="microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception" data-throw-if-not-resolved="false">ReentrancyModeDisallowedException</xref>指定したエラー メッセージを使用します。</p>
      <p></p>
    syntax:
      content: public ReentrancyModeDisallowedException(String message)
      parameters:
        - id: message
          type: '26831127'
          description: <p>例外メッセージ </p>
  - uid: 'microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException(String,Throwable)'
    id: 'ReentrancyModeDisallowedException(String,Throwable)'
    parent: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception
    href: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.yml
    langs:
      - java
    name: 'ReentrancyModeDisallowedException(String message, Throwable cause)'
    nameWithType: 'ReentrancyModeDisallowedException.ReentrancyModeDisallowedException(String message, Throwable cause)'
    fullName: 'microsoft.servicefabric.actors.ReentrancyModeDisallowedException.ReentrancyModeDisallowedException(String message, Throwable cause)'
    overload: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ReentrancyModeDisallowedException.java
      startLine: 31
    package: microsoft.servicefabric.actors
    summary: |-
      <p>新しいインスタンスを初期化、 <xref uid="microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception" data-throw-if-not-resolved="false">ReentrancyModeDisallowedException</xref>指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を持つクラス。</p>
      <p></p>
    syntax:
      content: 'public ReentrancyModeDisallowedException(String message, Throwable cause)'
      parameters:
        - id: message
          type: '26831127'
          description: <p>例外の原因を説明するエラー メッセージ。 </p>
        - id: cause
          type: a04fafd7
          description: <p>内部例外が指定されていない場合、現在の例外または null 参照の原因となった例外。 </p>
  - uid: 'microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException(String,Throwable,boolean,boolean)'
    id: 'ReentrancyModeDisallowedException(String,Throwable,boolean,boolean)'
    parent: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception
    href: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.yml
    langs:
      - java
    name: 'ReentrancyModeDisallowedException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    nameWithType: 'ReentrancyModeDisallowedException.ReentrancyModeDisallowedException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    fullName: 'microsoft.servicefabric.actors.ReentrancyModeDisallowedException.ReentrancyModeDisallowedException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    overload: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ReentrancyModeDisallowedException.java
      startLine: 71
    package: microsoft.servicefabric.actors
    summary: |-
      <p>新しいインスタンスを初期化、 <xref uid="microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception" data-throw-if-not-resolved="false">ReentrancyModeDisallowedException</xref>を指定したエラー メッセージ、 <xref uid="" data-throw-if-not-resolved="false">java.lang.Throwable</xref>が発生し、抑制を有効にして、印刷するフラグを付けますと 2 つのブール値スタック トレース。</p>
      <p></p>
    syntax:
      content: 'protected ReentrancyModeDisallowedException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
      parameters:
        - id: message
          type: '26831127'
          description: <p>例外メッセージ。 </p>
        - id: cause
          type: a04fafd7
          description: "<p>\r\n\r\n  <xref uid=\"\" data-throw-if-not-resolved=\"false\">java.lang.Throwable</xref>\r\n\r\n</p>"
        - id: enableSuppression
          type: 4fc6e284
          description: <p>True の場合は、抑制を有効にします。 </p>
        - id: writableStackTrace
          type: 4fc6e284
          description: <p>True の場合、スタック トレースを有効にします。 </p>
  - uid: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException(Throwable)
    id: ReentrancyModeDisallowedException(Throwable)
    parent: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception
    href: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.yml
    langs:
      - java
    name: ReentrancyModeDisallowedException(Throwable cause)
    nameWithType: ReentrancyModeDisallowedException.ReentrancyModeDisallowedException(Throwable cause)
    fullName: microsoft.servicefabric.actors.ReentrancyModeDisallowedException.ReentrancyModeDisallowedException(Throwable cause)
    overload: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/microsoft.servicefabric.actors/src/microsoft/servicefabric/actors/ReentrancyModeDisallowedException.java
      startLine: 53
    package: microsoft.servicefabric.actors
    summary: |-
      <p>新しいインスタンスを初期化、 <xref uid="microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception" data-throw-if-not-resolved="false">ReentrancyModeDisallowedException</xref>クラス、 <xref uid="" data-throw-if-not-resolved="false">java.lang.Throwable</xref>が発生します。</p>
      <p></p>
    syntax:
      content: public ReentrancyModeDisallowedException(Throwable cause)
      parameters:
        - id: cause
          type: a04fafd7
          description: "<p>\r\n\r\n  <xref uid=\"\" data-throw-if-not-resolved=\"false\">java.lang.Throwable</xref>\r\n\r\n</p>"
references:
  - uid: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.ReentrancyModeDisallowedException*
    name: ReentrancyModeDisallowedException
    nameWithType: ReentrancyModeDisallowedException.ReentrancyModeDisallowedException
    fullName: microsoft.servicefabric.actors.ReentrancyModeDisallowedException.ReentrancyModeDisallowedException
    package: microsoft.servicefabric.actors
  - uid: '26831127'
    spec.java:
      - name: String
        fullName: String
  - uid: a04fafd7
    spec.java:
      - name: Throwable
        fullName: Throwable
  - uid: 4fc6e284
    spec.java:
      - name: boolean
        fullName: boolean
  - uid: system.fabric.exception._fabric_exception.FabricException()
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException()
    nameWithType: FabricException.FabricException()
    fullName: system.fabric.exception.FabricException.FabricException()
    type: Constructor
    syntax:
      content: public FabricException()
  - uid: system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(FabricErrorCode errorCode)
    nameWithType: FabricException.FabricException(FabricErrorCode errorCode)
    fullName: system.fabric.exception.FabricException.FabricException(FabricErrorCode errorCode)
    type: Constructor
    syntax:
      content: public FabricException(FabricErrorCode errorCode)
      parameters:
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.FabricException(String)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(String message)
    nameWithType: FabricException.FabricException(String message)
    fullName: system.fabric.exception.FabricException.FabricException(String message)
    type: Constructor
    syntax:
      content: public FabricException(String message)
      parameters:
        - id: message
          type: '26831127'
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, Throwable cause)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.FabricException(Throwable)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(Throwable cause)
    nameWithType: FabricException.FabricException(Throwable cause)
    fullName: system.fabric.exception.FabricException.FabricException(Throwable cause)
    type: Constructor
    syntax:
      content: public FabricException(Throwable cause)
      parameters:
        - id: cause
          type: a04fafd7
  - uid: 'system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(Throwable cause, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(Throwable cause, FabricErrorCode errorCode)'
      parameters:
        - id: cause
          type: a04fafd7
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    type: Constructor
    syntax:
      content: 'protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.getErrorCode()
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: getErrorCode()
    nameWithType: FabricException.getErrorCode()
    fullName: FabricErrorCode system.fabric.exception.FabricException.getErrorCode()
    type: Method
    syntax:
      content: public FabricErrorCode getErrorCode()
      return:
        type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception
    parent: system.fabric.exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException
    nameWithType: FabricException
    fullName: system.fabric.exception.FabricException
    type: Class
    syntax:
      content: public class FabricException
  - uid: microsoft.servicefabric.actors._reentrancy_mode
    parent: microsoft.servicefabric.actors
    href: microsoft.servicefabric.actors._reentrancy_mode.yml
    name: ReentrancyMode
    nameWithType: ReentrancyMode
    fullName: microsoft.servicefabric.actors.ReentrancyMode
    type: Enum
    summary: <p>アクター メソッドの呼び出しのための再入モードを指定します。 </p>
    syntax:
      content: public enum ReentrancyMode
  - uid: microsoft.servicefabric.actors._reentrancy_mode.Disallowed
    parent: microsoft.servicefabric.actors._reentrancy_mode
    href: microsoft.servicefabric.actors._reentrancy_mode.yml
    name: Disallowed
    nameWithType: ReentrancyMode.Disallowed
    fullName: microsoft.servicefabric.actors.ReentrancyMode.Disallowed
    type: Field
    summary: <p>再入するアクターは許可されていません。 ここでは、アクターを送信する場合、再入メッセージを別のアクター型の例外<xref uid="system.fabric.exception._fabric_exception" data-throw-if-not-resolved="false">system.fabric.exception.FabricException</xref>がスローされます。 </p>
    syntax:
      content: public Disallowed=(2)
  - uid: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception
    parent: microsoft.servicefabric.actors
    href: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.yml
    name: ReentrancyModeDisallowedException
    nameWithType: ReentrancyModeDisallowedException
    fullName: microsoft.servicefabric.actors.ReentrancyModeDisallowedException
    type: Class
    summary: '<p>アクターの再入可能呼び出しが行われたときにアクター ランタイムによってスローされる例外とその<xref uid="microsoft.servicefabric.actors._reentrancy_mode" data-throw-if-not-resolved="false">ReentrancyMode</xref>に設定されている<xref uid="microsoft.servicefabric.actors._reentrancy_mode.Disallowed" data-throw-if-not-resolved="false">ReentrancyMode #Disallowed</xref>です。 </p>'
    syntax: *ref_1