### YamlMime:ManagedReference
items:
  - uid: system.fabric.exception._fabric_connection_denied_exception
    id: _fabric_connection_denied_exception
    parent: system.fabric.exception
    children:
      - system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException()
      - system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException(String)
      - 'system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException(String,Throwable)'
      - 'system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException(String,Throwable,boolean,boolean)'
      - system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException(Throwable)
    href: system.fabric.exception._fabric_connection_denied_exception.yml
    langs:
      - java
    name: FabricConnectionDeniedException
    nameWithType: FabricConnectionDeniedException
    fullName: system.fabric.exception.FabricConnectionDeniedException
    type: Class
    source:
      remote: &ref_0
        path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricConnectionDeniedException.java
        branch: master
        repo: 'https://msazure.visualstudio.com/One/_git/sf-java'
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricConnectionDeniedException.java
      startLine: 5
    package: system.fabric.exception
    summary: <p><span data-ttu-id="c58ab-101">接続が拒否された場合にスローされる例外。</span><span class="sxs-lookup"><span data-stu-id="c58ab-101">The exception that is thrown when connection is denied.</span></span> </p>
    syntax: &ref_1
      content: public class FabricConnectionDeniedException extends FabricException
    inheritance:
      - java.lang.Object
      - RuntimeException
      - system.fabric.exception._fabric_exception
    inheritedMembers:
      - system.fabric.exception._fabric_exception.FabricException()
      - system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
      - system.fabric.exception._fabric_exception.FabricException(String)
      - 'system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)'
      - system.fabric.exception._fabric_exception.FabricException(Throwable)
      - 'system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)'
      - system.fabric.exception._fabric_exception.getErrorCode()
  - uid: system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException()
    id: FabricConnectionDeniedException()
    parent: system.fabric.exception._fabric_connection_denied_exception
    href: system.fabric.exception._fabric_connection_denied_exception.yml
    langs:
      - java
    name: FabricConnectionDeniedException()
    nameWithType: FabricConnectionDeniedException.FabricConnectionDeniedException()
    fullName: system.fabric.exception.FabricConnectionDeniedException.FabricConnectionDeniedException()
    overload: system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricConnectionDeniedException.java
      startLine: 13
    package: system.fabric.exception
    summary: <p><span data-ttu-id="c58ab-102">新しいインスタンスを初期化、 <xref uid="system.fabric.exception._fabric_connection_denied_exception" data-throw-if-not-resolved="false">FabricConnectionDeniedException</xref>クラスです。</span><span class="sxs-lookup"><span data-stu-id="c58ab-102">Initializes a new instance of the <xref uid="system.fabric.exception._fabric_connection_denied_exception" data-throw-if-not-resolved="false">FabricConnectionDeniedException</xref> class.</span></span> </p>
    syntax:
      content: public FabricConnectionDeniedException()
  - uid: system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException(String)
    id: FabricConnectionDeniedException(String)
    parent: system.fabric.exception._fabric_connection_denied_exception
    href: system.fabric.exception._fabric_connection_denied_exception.yml
    langs:
      - java
    name: FabricConnectionDeniedException(String message)
    nameWithType: FabricConnectionDeniedException.FabricConnectionDeniedException(String message)
    fullName: system.fabric.exception.FabricConnectionDeniedException.FabricConnectionDeniedException(String message)
    overload: system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricConnectionDeniedException.java
      startLine: 38
    package: system.fabric.exception
    summary: |-
      <p><span data-ttu-id="c58ab-103">新しいインスタンスを初期化、 <xref uid="system.fabric.exception._fabric_connection_denied_exception" data-throw-if-not-resolved="false">FabricConnectionDeniedException</xref>指定したエラー メッセージを使用します。</span><span class="sxs-lookup"><span data-stu-id="c58ab-103">Initializes a new instance of the <xref uid="system.fabric.exception._fabric_connection_denied_exception" data-throw-if-not-resolved="false">FabricConnectionDeniedException</xref> class with a specified error message.</span></span></p>
      <p></p>
    syntax:
      content: public FabricConnectionDeniedException(String message)
      parameters:
        - id: message
          type: '26831127'
          description: <p><span data-ttu-id="c58ab-104">例外の原因を説明するエラー メッセージ。</span><span class="sxs-lookup"><span data-stu-id="c58ab-104">The error message that explains the reason for the exception.</span></span> </p>
  - uid: 'system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException(String,Throwable)'
    id: 'FabricConnectionDeniedException(String,Throwable)'
    parent: system.fabric.exception._fabric_connection_denied_exception
    href: system.fabric.exception._fabric_connection_denied_exception.yml
    langs:
      - java
    name: 'FabricConnectionDeniedException(String message, Throwable cause)'
    nameWithType: 'FabricConnectionDeniedException.FabricConnectionDeniedException(String message, Throwable cause)'
    fullName: 'system.fabric.exception.FabricConnectionDeniedException.FabricConnectionDeniedException(String message, Throwable cause)'
    overload: system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricConnectionDeniedException.java
      startLine: 27
    package: system.fabric.exception
    summary: |-
      <p><span data-ttu-id="c58ab-105">新しいインスタンスを初期化、 <xref uid="system.fabric.exception._fabric_connection_denied_exception" data-throw-if-not-resolved="false">FabricConnectionDeniedException</xref>クラスは、指定したエラー メッセージとエラー コード。</span><span class="sxs-lookup"><span data-stu-id="c58ab-105">Initializes a new instance of the <xref uid="system.fabric.exception._fabric_connection_denied_exception" data-throw-if-not-resolved="false">FabricConnectionDeniedException</xref> class with a specified error message and error code.</span></span></p>
      <p></p>
    syntax:
      content: 'public FabricConnectionDeniedException(String message, Throwable cause)'
      parameters:
        - id: message
          type: '26831127'
          description: <p><span data-ttu-id="c58ab-106">例外の原因を説明するエラー メッセージ。</span><span class="sxs-lookup"><span data-stu-id="c58ab-106">The error message that explains the reason for the exception.</span></span> </p>
        - id: cause
          type: a04fafd7
          description: '<p><span data-ttu-id="c58ab-107">内部例外が指定されていない場合、現在の例外または null 参照の原因となった例外。</span><span class="sxs-lookup"><span data-stu-id="c58ab-107">The exception that is the cause of the current exception, or a null reference if no inner exception is specified.</span></span> </p>'
  - uid: 'system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException(String,Throwable,boolean,boolean)'
    id: 'FabricConnectionDeniedException(String,Throwable,boolean,boolean)'
    parent: system.fabric.exception._fabric_connection_denied_exception
    href: system.fabric.exception._fabric_connection_denied_exception.yml
    langs:
      - java
    name: 'FabricConnectionDeniedException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    nameWithType: 'FabricConnectionDeniedException.FabricConnectionDeniedException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    fullName: 'system.fabric.exception.FabricConnectionDeniedException.FabricConnectionDeniedException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    overload: system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricConnectionDeniedException.java
      startLine: 46
    package: system.fabric.exception
    syntax:
      content: 'protected FabricConnectionDeniedException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
  - uid: system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException(Throwable)
    id: FabricConnectionDeniedException(Throwable)
    parent: system.fabric.exception._fabric_connection_denied_exception
    href: system.fabric.exception._fabric_connection_denied_exception.yml
    langs:
      - java
    name: FabricConnectionDeniedException(Throwable cause)
    nameWithType: FabricConnectionDeniedException.FabricConnectionDeniedException(Throwable cause)
    fullName: system.fabric.exception.FabricConnectionDeniedException.FabricConnectionDeniedException(Throwable cause)
    overload: system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricConnectionDeniedException.java
      startLine: 42
    package: system.fabric.exception
    syntax:
      content: public FabricConnectionDeniedException(Throwable cause)
      parameters:
        - id: cause
          type: a04fafd7
references:
  - uid: system.fabric.exception._fabric_connection_denied_exception.FabricConnectionDeniedException*
    name: FabricConnectionDeniedException
    nameWithType: FabricConnectionDeniedException.FabricConnectionDeniedException
    fullName: system.fabric.exception.FabricConnectionDeniedException.FabricConnectionDeniedException
    package: system.fabric.exception
  - uid: '26831127'
    spec.java:
      - name: String
        fullName: String
  - uid: a04fafd7
    spec.java:
      - name: Throwable
        fullName: Throwable
  - uid: 4fc6e284
    spec.java:
      - name: boolean
        fullName: boolean
  - uid: system.fabric.exception._fabric_exception.FabricException()
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException()
    nameWithType: FabricException.FabricException()
    fullName: system.fabric.exception.FabricException.FabricException()
    type: Constructor
    syntax:
      content: public FabricException()
  - uid: system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(FabricErrorCode errorCode)
    nameWithType: FabricException.FabricException(FabricErrorCode errorCode)
    fullName: system.fabric.exception.FabricException.FabricException(FabricErrorCode errorCode)
    type: Constructor
    syntax:
      content: public FabricException(FabricErrorCode errorCode)
      parameters:
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.FabricException(String)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(String message)
    nameWithType: FabricException.FabricException(String message)
    fullName: system.fabric.exception.FabricException.FabricException(String message)
    type: Constructor
    syntax:
      content: public FabricException(String message)
      parameters:
        - id: message
          type: '26831127'
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, Throwable cause)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.FabricException(Throwable)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(Throwable cause)
    nameWithType: FabricException.FabricException(Throwable cause)
    fullName: system.fabric.exception.FabricException.FabricException(Throwable cause)
    type: Constructor
    syntax:
      content: public FabricException(Throwable cause)
      parameters:
        - id: cause
          type: a04fafd7
  - uid: 'system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(Throwable cause, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(Throwable cause, FabricErrorCode errorCode)'
      parameters:
        - id: cause
          type: a04fafd7
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    type: Constructor
    syntax:
      content: 'protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.getErrorCode()
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: getErrorCode()
    nameWithType: FabricException.getErrorCode()
    fullName: FabricErrorCode system.fabric.exception.FabricException.getErrorCode()
    type: Method
    syntax:
      content: public FabricErrorCode getErrorCode()
      return:
        type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception
    parent: system.fabric.exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException
    nameWithType: FabricException
    fullName: system.fabric.exception.FabricException
    type: Class
    syntax:
      content: public class FabricException
  - uid: system.fabric.exception._fabric_connection_denied_exception
    parent: system.fabric.exception
    href: system.fabric.exception._fabric_connection_denied_exception.yml
    name: FabricConnectionDeniedException
    nameWithType: FabricConnectionDeniedException
    fullName: system.fabric.exception.FabricConnectionDeniedException
    type: Class
    summary: <p><span data-ttu-id="c58ab-108">接続が拒否された場合にスローされる例外。</span><span class="sxs-lookup"><span data-stu-id="c58ab-108">The exception that is thrown when connection is denied.</span></span> </p>
    syntax: *ref_1