### YamlMime:ManagedReference
items:
  - uid: system.fabric.exception._fabric_cannot_connect_exception
    id: _fabric_cannot_connect_exception
    parent: system.fabric.exception
    children:
      - system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException()
      - system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(String)
      - 'system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(String,Throwable)'
      - 'system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(String,Throwable,boolean,boolean)'
      - 'system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(String,Throwable,FabricErrorCode)'
      - system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(Throwable)
    href: system.fabric.exception._fabric_cannot_connect_exception.yml
    langs:
      - java
    name: FabricCannotConnectException
    nameWithType: FabricCannotConnectException
    fullName: system.fabric.exception.FabricCannotConnectException
    type: Class
    source:
      remote: &ref_0
        path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricCannotConnectException.java
        branch: master
        repo: 'https://msazure.visualstudio.com/One/_git/sf-java'
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricCannotConnectException.java
      startLine: 4
    package: system.fabric.exception
    syntax: &ref_1
      content: public class FabricCannotConnectException extends FabricException
    inheritance:
      - java.lang.Object
      - RuntimeException
      - system.fabric.exception._fabric_exception
    inheritedMembers:
      - system.fabric.exception._fabric_exception.FabricException()
      - system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
      - system.fabric.exception._fabric_exception.FabricException(String)
      - 'system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)'
      - system.fabric.exception._fabric_exception.FabricException(Throwable)
      - 'system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)'
      - system.fabric.exception._fabric_exception.getErrorCode()
  - uid: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException()
    id: FabricCannotConnectException()
    parent: system.fabric.exception._fabric_cannot_connect_exception
    href: system.fabric.exception._fabric_cannot_connect_exception.yml
    langs:
      - java
    name: FabricCannotConnectException()
    nameWithType: FabricCannotConnectException.FabricCannotConnectException()
    fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException()
    overload: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricCannotConnectException.java
      startLine: 11
    package: system.fabric.exception
    syntax:
      content: public FabricCannotConnectException()
  - uid: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(String)
    id: FabricCannotConnectException(String)
    parent: system.fabric.exception._fabric_cannot_connect_exception
    href: system.fabric.exception._fabric_cannot_connect_exception.yml
    langs:
      - java
    name: FabricCannotConnectException(String message)
    nameWithType: FabricCannotConnectException.FabricCannotConnectException(String message)
    fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String message)
    overload: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricCannotConnectException.java
      startLine: 52
    package: system.fabric.exception
    summary: |-
      <p>新しいインスタンスを初期化、 <xref uid="system.fabric.exception._fabric_cannot_connect_exception" data-throw-if-not-resolved="false">FabricCannotConnectException</xref>指定したエラー メッセージを使用します。</p>
      <p></p>
    syntax:
      content: public FabricCannotConnectException(String message)
      parameters:
        - id: message
          type: '26831127'
          description: <p>例外の原因を説明するエラー メッセージ。 </p>
  - uid: 'system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(String,Throwable)'
    id: 'FabricCannotConnectException(String,Throwable)'
    parent: system.fabric.exception._fabric_cannot_connect_exception
    href: system.fabric.exception._fabric_cannot_connect_exception.yml
    langs:
      - java
    name: 'FabricCannotConnectException(String message, Throwable cause)'
    nameWithType: 'FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause)'
    fullName: 'system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause)'
    overload: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricCannotConnectException.java
      startLine: 25
    package: system.fabric.exception
    summary: |-
      <p>新しいインスタンスを初期化、 <xref uid="system.fabric.exception._fabric_cannot_connect_exception" data-throw-if-not-resolved="false">FabricCannotConnectException</xref>クラスは、指定したエラー メッセージとエラー コード。</p>
      <p></p>
    syntax:
      content: 'public FabricCannotConnectException(String message, Throwable cause)'
      parameters:
        - id: message
          type: '26831127'
          description: <p>例外の原因を説明するエラー メッセージ。 </p>
        - id: cause
          type: a04fafd7
          description: <p>内部例外が指定されていない場合、現在の例外または null 参照の原因となった例外。 </p>
  - uid: 'system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(String,Throwable,boolean,boolean)'
    id: 'FabricCannotConnectException(String,Throwable,boolean,boolean)'
    parent: system.fabric.exception._fabric_cannot_connect_exception
    href: system.fabric.exception._fabric_cannot_connect_exception.yml
    langs:
      - java
    name: 'FabricCannotConnectException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    nameWithType: 'FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    fullName: 'system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    overload: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricCannotConnectException.java
      startLine: 60
    package: system.fabric.exception
    syntax:
      content: 'protected FabricCannotConnectException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
  - uid: 'system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(String,Throwable,FabricErrorCode)'
    id: 'FabricCannotConnectException(String,Throwable,FabricErrorCode)'
    parent: system.fabric.exception._fabric_cannot_connect_exception
    href: system.fabric.exception._fabric_cannot_connect_exception.yml
    langs:
      - java
    name: 'FabricCannotConnectException(String message, Throwable cause, FabricErrorCode errorCode)'
    nameWithType: 'FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause, FabricErrorCode errorCode)'
    overload: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricCannotConnectException.java
      startLine: 41
    package: system.fabric.exception
    summary: |-
      <p>新しいインスタンスを初期化、 <xref uid="system.fabric.exception._fabric_cannot_connect_exception" data-throw-if-not-resolved="false">FabricCannotConnectException</xref>クラスは、指定したエラー メッセージとエラー コード。</p>
      <p></p>
    syntax:
      content: 'public FabricCannotConnectException(String message, Throwable cause, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
          description: <p>例外の原因を説明するエラー メッセージ。 </p>
        - id: cause
          type: a04fafd7
          description: <p>内部例外が指定されていない場合、現在の例外または null 参照の原因となった例外。 </p>
        - id: errorCode
          type: system.fabric._fabric_error_code
          description: <p>例外の ErrorCode </p>
  - uid: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException(Throwable)
    id: FabricCannotConnectException(Throwable)
    parent: system.fabric.exception._fabric_cannot_connect_exception
    href: system.fabric.exception._fabric_cannot_connect_exception.yml
    langs:
      - java
    name: FabricCannotConnectException(Throwable cause)
    nameWithType: FabricCannotConnectException.FabricCannotConnectException(Throwable cause)
    fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(Throwable cause)
    overload: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricCannotConnectException.java
      startLine: 56
    package: system.fabric.exception
    syntax:
      content: public FabricCannotConnectException(Throwable cause)
      parameters:
        - id: cause
          type: a04fafd7
references:
  - uid: system.fabric.exception._fabric_cannot_connect_exception.FabricCannotConnectException*
    name: FabricCannotConnectException
    nameWithType: FabricCannotConnectException.FabricCannotConnectException
    fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException
    package: system.fabric.exception
  - uid: '26831127'
    spec.java:
      - name: String
        fullName: String
  - uid: a04fafd7
    spec.java:
      - name: Throwable
        fullName: Throwable
  - uid: 4fc6e284
    spec.java:
      - name: boolean
        fullName: boolean
  - uid: system.fabric.exception._fabric_exception.FabricException()
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException()
    nameWithType: FabricException.FabricException()
    fullName: system.fabric.exception.FabricException.FabricException()
    type: Constructor
    syntax:
      content: public FabricException()
  - uid: system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(FabricErrorCode errorCode)
    nameWithType: FabricException.FabricException(FabricErrorCode errorCode)
    fullName: system.fabric.exception.FabricException.FabricException(FabricErrorCode errorCode)
    type: Constructor
    syntax:
      content: public FabricException(FabricErrorCode errorCode)
      parameters:
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.FabricException(String)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(String message)
    nameWithType: FabricException.FabricException(String message)
    fullName: system.fabric.exception.FabricException.FabricException(String message)
    type: Constructor
    syntax:
      content: public FabricException(String message)
      parameters:
        - id: message
          type: '26831127'
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, Throwable cause)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.FabricException(Throwable)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(Throwable cause)
    nameWithType: FabricException.FabricException(Throwable cause)
    fullName: system.fabric.exception.FabricException.FabricException(Throwable cause)
    type: Constructor
    syntax:
      content: public FabricException(Throwable cause)
      parameters:
        - id: cause
          type: a04fafd7
  - uid: 'system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(Throwable cause, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(Throwable cause, FabricErrorCode errorCode)'
      parameters:
        - id: cause
          type: a04fafd7
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    type: Constructor
    syntax:
      content: 'protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.getErrorCode()
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: getErrorCode()
    nameWithType: FabricException.getErrorCode()
    fullName: FabricErrorCode system.fabric.exception.FabricException.getErrorCode()
    type: Method
    syntax:
      content: public FabricErrorCode getErrorCode()
      return:
        type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception
    parent: system.fabric.exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException
    nameWithType: FabricException
    fullName: system.fabric.exception.FabricException
    type: Class
    syntax:
      content: public class FabricException
  - uid: system.fabric.exception._fabric_cannot_connect_exception
    parent: system.fabric.exception
    href: system.fabric.exception._fabric_cannot_connect_exception.yml
    name: FabricCannotConnectException
    nameWithType: FabricCannotConnectException
    fullName: system.fabric.exception.FabricCannotConnectException
    type: Class
    syntax: *ref_1
  - uid: system.fabric._fabric_error_code
    parent: system.fabric
    href: system.fabric._fabric_error_code.yml
    name: FabricErrorCode
    nameWithType: FabricErrorCode
    fullName: system.fabric.FabricErrorCode
    type: Enum
    syntax:
      content: public enum FabricErrorCode